version: 2.1

defaults: &defaults
  docker:
    - image: cimg/node:16.13.1-browsers
  working_directory: ~/qiaroq-react

jobs:
  install:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: "."
          paths:
            - "package.json"
            - "package-lock.json"
            - "project.json"
            - "jest.*.js"
            - "webpack.*.js"
            - ".babelrc"
            - ".eslintrc"
            - "node_modules"
            - "src/*"

  format:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/qiaroq-react
      - run:
          name: Format
          command: npm run format

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/qiaroq-react
      - run:
          name: Build
          command: NODE_ENV=production npm run build

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/qiaroq-react
      - run:
          name: Test
          command: npm run test -- --maxWorkers=2 --coverage --coverageReporters=lcov

workflows:
  version: 2

  branch-workflow:
    jobs:
      - install
      - format:
          requires:
            - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install
